# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/centralnode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/centralnode.proto\x12\x05proto\"\x13\n\x02id\x12\r\n\x05id_av\x18\x01 \x01(\t\"\x16\n\x04\x63ode\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32,\n\x07SendACK\x12!\n\x07sendACK\x12\t.proto.id\x1a\x0b.proto.codeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.centralnode_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ID._serialized_start=34
  _ID._serialized_end=53
  _CODE._serialized_start=55
  _CODE._serialized_end=77
  _SENDACK._serialized_start=79
  _SENDACK._serialized_end=123
# @@protoc_insertion_point(module_scope)
